export const ProductConstant = {
    PRODUCT_REQUEST : "PRODUCT_REQUEST",
    PRODUCT_LIST_SUCCESS : "PRODUCT_LIST_SUCCESS",

    FILTER_UPDATE : "FILTER_UPDATE",
    PRODUCT_FILTER : "PRODUCT_FILTER",

    FITER_CATEGORY : "FITER_CATEGORY",
    
    PRODUCT_FAIL : "PRODUCT_FAIL",
}